name: Release Deployment


on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Modify the Environment variables to meet your requirements
    env:
      BUILD_OUTPUT_FOLDER: ./build
      S3_BUCKET_NAME: finsemble-sd-v6

    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Update AppD URL
        run:  node ./gh-action.js

      # This section can be modified where needed
      - name: Production Deploy
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'}}
        run: aws s3 sync $BUILD_OUTPUT_FOLDER s3://$S3_BUCKET_NAME/production/$GITHUB_REPOSITORY --acl public-read
